### ISSUE TITLE
promise support

### ISSUE THREAD

**Issue by wtcross** [Bandwidth/node-bandwidth#11]
If a callback is not passed to any method then a promise should be returned. I'd like to suggest using [Bluebird](https://github.com/petkaantonov/bluebird). Here is an example of "promisifying" the existing library in one of my applications;

``` javascript
var Catapult = require("node-bandwidth");
var Bluebird = require("bluebird");

Bluebird.promisifyAll(Catapult.Message);

var client = new Catapult.Client({
    apiToken  : process.env.BANDWIDTH_API_TOKEN,
    apiSecret : process.env.BANDWIDTH_API_SECRET,
    userId    : process.env.BANDWIDTH_USER_ID
})

Catapult.Message.createAsync(client, {
    to   : "+19199463223",
    from : "+15713170274",
    text : "this is a test"
})
.then(function (message) {
    console.log("sent message: " + JSON.stringify(message));
})
.catch(function (err) {
    console.log("failed to send message: " + message);
});
```

**Comment by nguyer** [comment]
I agree that this would be convenient for a lot of us, but what if someone wants to use something other than Bluebird? This seems to be the sort of thing that might be best left up to the SDK consumer to determine how they want to wrap promises (if they even need to).

**Comment by avbel** [comment]
Node 0.12+ has native Promises.
22 июня 2015 г. 22:14 пользователь "Nicko Guyer" notifications@github.com
написал:

**Comment by nguyer** [comment]
@avbel True, although Bluebird promises are significantly faster and less memory intensive than ES6 native promises, so I'm also hesitant about going that route.

**Comment by jagoda** [comment]
@nguyer is this to say that the current SDK strategy is to mimic the Node API callback style for all async functions?

**Comment by jagoda** [comment]
@avbel we should be sensitive to whether or not any consumers are using Node 0.10.

**Comment by nguyer** [comment]
@jagoda That is definitely how it is currently, though it's worth the discussion of whether or not to change that approach (or add additional features). I'm not dead set on any one approach yet.

**Comment by jagoda** [comment]
Cool, just making sure that I'm following this. I don't have a strong preference as to what is chosen here so long as the decision/assumptions are explicit and consistently followed.

**Comment by nguyer** [comment]
Yeah. I think we should decide what our criteria is for adding features.

1) Do we value ease of use the most by adding lots of convenience features, though possibly sacrificing compatibility if people aren't using the same libraries?

2) Do we value using the latest and greatest standardized (ES6) features, perhaps leaving behind users that aren't using the latest and greatest?

3) Do we value maximum compatibility with users across many versions and other libraries, which may mean not including some convenience features?

I think for an SDK it should be a balance of the 1 and 3, though I'm also also of the opinion that we should try to keep the SDK as lightweight as possible by not including lots of third party libraries when we don't have to.
