### ISSUE TITLE
Downloading mms image files

### ISSUE THREAD

**Issue by ryanmcclure4** [Bandwidth/node-bandwidth#111]
I'm using Media.download to download an image file from an mms, and I'm having trouble processing the response body content.

A typical response looks like this:

```
{
  contentType: 'image/jpeg;name=image000000-m-c5qhcr3dxokuvrqpraiqxli.jpg',
  content: '����\u0000\u0010JFIF\u0000\u0001\u0001...
}
```

I can't seem to successfully save this content to a file and open it as an image. Is there some type of encoding that needs to be performed on this response?

---

I've submitted a pull request to fix this issue #112

**Comment by nguyer** [comment]
Thanks for opening this! I'll take a look at your PR.

**Comment by dtolb** [comment]
Addressing in PR [#116](https://github.com/bandwidthcom/node-bandwidth/pull/116)

**Comment by dtolb** [comment]
In release [v2.3.0](https://github.com/bandwidthcom/node-bandwidth/releases/tag/v2.3.0)

**Comment by btknorr** [comment]
Still getting this type of response with release 2.3.0:

{
  contentType: 'image/jpeg;name=image000000-m-c5qhcr3dxokuvrqpraiqxli.jpg',
  content: '����\u0000\u0010JFIF\u0000\u0001\u0001...
}

Please re-open...

**Comment by dtolb** [comment]
Encoding changed to `binary` in 

* PR [#119](https://github.com/bandwidthcom/node-bandwidth/pull/119)
* Release [v2.3.1](https://github.com/bandwidthcom/node-bandwidth/releases/tag/v2.3.1)
* NPM Package [v2.3.1](https://www.npmjs.com/package/node-bandwidth)
