### ISSUE TITLE
BXML Phone Number Verb

### ISSUE THREAD

**Issue by mharis** [Bandwidth/node-bandwidth#114]
For multi-transfer, you need to add phone number verb inside the transfer verb which isn't possible now with node-bandwith.

http://ap.bandwidth.com/docs/xml/transfer/

**Comment by dtolb** [comment]
@mharis Thanks for opening the issue.

I'll take a look. 

:man_dancing:

**Comment by dtolb** [comment]
@mharis 

Should be fixed in [PR 115](https://github.com/bandwidthcom/node-bandwidth/pull/115).

Look for a new version bump sometime next week!

**Comment by mharis** [comment]
Thank you ! :)

**Comment by dtolb** [comment]
In [v2.3.0](https://github.com/bandwidthcom/node-bandwidth/releases/tag/v2.3.0)
