### ISSUE TITLE
Filter messages by deliveryState 'not-delivered' fails with error

### ISSUE THREAD

**Issue by btknorr** [Bandwidth/node-bandwidth#120]
```
client.Message.list({deliveryState:'not-delivered'}, function(err, result) { console.log(err); });
```
results in the following error in the console:
```
{ [The 'deliveryState' parameter is the wrong type or does not follow the required format.]
  name: '',
  message: 'The \'deliveryState\' parameter is the wrong type or does not follow the required format.',
  statusCode: 400 }
```

**Comment by dtolb** [comment]
@btknorr Thanks for opening the issue! 

We're looking into the root issue, the node-sdk simply passes the parameters from your JSON to the API.  There may be an issue somewhere in the SDK, but for now stay tuned for any updates via the support ticket.

I'm going to close this issue as it's not directly related to the SDK, but may re-open upon further investigation.

Cheers,
DT

![screen capture on 2017-03-09 at 09-52-50](https://cloud.githubusercontent.com/assets/6805534/23755518/9ff38212-04ae-11e7-93bf-c91239c3e27e.gif)
