### ISSUE TITLE
branch: local-v2 message.sendGroup promise error

### ISSUE THREAD

**Issue by yardensk** [Bandwidth/node-bandwidth#124]
in file:
https://github.com/bandwidthcom/node-bandwidth/blob/local-v2/lib/message.js
line: 110
causes error:

> TypeError: Cannot read property 'substring' of undefined

replace:

`message.id = location.substring(location.lastIndexOf("/") + 1);
`
with

`message.id = response.body.id;
`

**Comment by dtolb** [comment]
resolved in [125](https://github.com/bandwidthcom/node-bandwidth/pull/125)
