### ISSUE TITLE
Can’t purchase a specific number

### ISSUE THREAD

**Issue by natesilva** [Bandwidth/node-bandwidth#141]
When ordering phone numbers, there is no way to specify a pattern. At least, I couldn’t find it in the API documentation at https://github.com/bandwidthcom/node-bandwidth/blob/master/docs/api.md#availablenumbersearchandordertype-params-callback--arrayorderednumberresponse

When **searching** for phone numbers, the `pattern` option works fine, but that is not available when purchasing -- so I can’t figure out how to purchase specific available numbers.

**Comment by dtolb** [comment]
@natesilva Good catch! The docs are missing the `pattern` parameter in the `searchAndOrder` function. I updated in [PR 142](https://github.com/bandwidthcom/node-bandwidth/pull/142).

Also, you can use the [`search`](https://github.com/bandwidthcom/node-bandwidth/blob/master/docs/api.md#availablenumbersearchtype-params-callback--arrayavailablenumberresponse) method to feed into the [`PhoneNumber.create`](https://github.com/bandwidthcom/node-bandwidth/blob/master/docs/api.md#PhoneNumber+create) method.

Here is a snip demonstrating the differences:

```js
const Bandwidth = require("node-bandwidth");
const client = new Bandwidth({
    userId    : process.env.BANDWIDTH_USER_ID,
    apiToken  : process.env.BANDWIDTH_API_TOKEN,
    apiSecret : process.env.BANDWIDTH_API_SECRET,
});

const searchThenOrder = function () {
    console.log("Searching THEN Ordering numbers in 2 steps");
    return client.AvailableNumber.search("local", {
        city     : "Cary",
        state    : "NC",
        pattern  : "*2?9*",
        quantity : 1,
    })
    .then(function (numbers) {
        console.log("Found Numbers:");
        console.log(numbers);
        const number = numbers[0].number;
        return client.PhoneNumber.create({number});
    })
    .then(function (orderedNumber) {
        console.log("Ordered Number")
        console.log(orderedNumber);
        return orderedNumber;
    })
    .catch(function (error) {
        console.log("Something went wrong searching THEN ordering numbers")
        console.log(error);
    });
}


const searchAndOrder = function () {
    console.log("Searching AND Ordering Numbers in 1 step")
    return client.AvailableNumber.searchAndOrder("local", {
        city     : "Cary",
        state    : "NC",
        pattern  : "*2?9*",
        quantity : 1,
    })
    .then(function (orderedNumber) {
        console.log("Ordered Number")
        console.log(orderedNumber);
        return orderedNumber;
    })
    .catch(function (error) {
        console.log("Something went wrong searching AND ordering numbers")
        console.log(error);
    });
}

const main = async function () {
    const newNumber1 = await searchThenOrder();
    const newNumber2 = await searchAndOrder();
}

main();
```

Unfortunately, there is not a way to `searchAndOrder` as well as assign the phone number to an [application](http://dev.bandwidth.com/ap-docs/methods/applications/applications.html) for incoming calls and texts in a _single_ API call. You can either `searchAndOrder` then [`update`](https://github.com/bandwidthcom/node-bandwidth/blob/master/docs/api.md#phonenumberupdatephonenumberid-params-callback--promise) the update the phone number.

Or, you can `search` then use the [`PhoneNumber.create`](https://github.com/bandwidthcom/node-bandwidth/blob/master/docs/api.md#PhoneNumber+create) method and specify the `applicationId` there.

Hope that helps!
-DT

**Comment by natesilva** [comment]
Thank you @dtolb. That explanation helped a ton.
