### ISSUE TITLE
vNext API suggestions

### ISSUE THREAD

**Issue by a-type** [Bandwidth/node-bandwidth#145]
Feedback, in order, while reviewing the `v-next` branch:

#### Supported language versions

Sorry to be blunt, but **asking developers to transpile their code or use only the latest version of Node is unreasonable for a mainline SDK**. I don't know of any other (popular) library which does this. The library should be responsible for transpiling its source using Babel or TS before shipping. Libraries can also provide alternate main files which target specific module systems.

#### Async iterators

I consider myself fairly seasoned in JS development, but I've never seen async iterator syntax before. Looks similar to generators (and I saw a generator in the code under the hood). I'm confused as to why there are two `await` statements. The [proposal](https://github.com/tc39/proposal-async-iteration) uses the `for await (... of` syntax and does not include multiple `await` statements. I'm guessing this is because the method itself which returns the iterator is asynchronous. This indicates to me that this iteration usage was kind of shoehorned into a pattern which wasn't designed to support it.

Really, I think this syntax is too new for expected adoption. I question the removal of `fetchNextPage` or similar helpers to assist developers who do not want to use iterators, which I imagine will be the majority. `fetchNextPage` is very easy to understand and would be useful as a promise-based tool within this library. As a developer I'd prefer to have the simplest tools immediately available and be able to extend the experience using advanced tools if I want to. I think it would make more sense to have `fetchNextPage` be the default packaged solution for iterating through pages, and then provide a helper from the library like `createItemIterator()` which would allow me to use an async iterator instead if I choose to construct one. A Node 8 user should be able to just ignore async iterators altogether and get on with developing the way they're used to.

```js
const firstPage = await api.calls.list();
// user can now access first page items as usual.
firstPage.forEach(message => console.log(message.text));
// user can also easily iterate pages with familiar concepts
const secondPage = await firstPage.fetchNextPage();
// or, user can iterate through items without worrying about pagination
const itemIterator = createItemIterator(firstPage);
for await (const message of itemIterator) {
  console.log(message.text);
}
// OR, the user can iterate through pages
const pageIterator = createPageIterator(firstPage);
for await (const page of pageIterator) {
  page.forEach(message => console.log(message.text);
}
```

This also solves the design problem where the `.list()` method returns entirely different kinds of objects depending on whether you passed in a `{ page }` parameter or not. Methods should return the same type no matter what you pass in.

#### Client instantiation

Top-level client creation should be a class instantiation, not a function call. Under the hood a `Proxy` class is being created around a `BandwidthApi` class already. Obscuring this behind a function call is odd and only seems to be necessary because of the Proxy usage. See more thoughts on Proxy below.

#### Naming conventions

Top-level properties for domains of api calls are just groupings, and should not be capitalized. Capitalized names are for class references only in standard JS formatting.

```js
api.Calls.get --> api.calls.get
```

#### Leaking implementation concerns

The library should not expose any details about the underlying HTTP tooling it uses to make requests. If you want to support cancellation of requests, it should be through a generic means, not by requiring the user to reference the `axios` library.

#### Documentation

Language / typos / mistakes in Readme would need to be cleaned up as well, but that's pretty standard stuff.

#### Proxies

Proxy usage seems confusing and unnecessary. It seems simpler and more maintainable just to assign properties directly to the `BandwidthApi` class, either statically or dynamically. "ApiObject"s seem to be generated lazily at runtime based on access. I don't see the advantage of such a complicated access pattern besides negligible memory saving. I would expect instantiation to look more like this:

```js
import apiData from './apiData';

class BandwidthApi {
  constructor(options = {}) {
    // the following create a nested map structure:
    // { Calls: { get: [Function bound to this], list: [Function bound to this]...
    const bindApiMethods = obj => Object.keys(obj).reduce((methods, key) => ({
      ...methods,
      [key]: this.createApiMethod(obj[key]).bind(this),
    }, {});
	const apiObjects = apiData.reduce((structured, obj) => ({
      ...structured,
      [obj.name]: bindApiMethods(obj),
    }, {});

    // now all bound API domain objects are accessible from this instance.
    Object.assign(this, apiObjects);
  }
}
```

Basically, the way you've used Proxy adds a lot of indirection and slight-of-hand to the way the code operates. This does not encourage outside contribution. Even though I understand what a Proxy is, I still have a hard time following the path a function call takes through the client object, how it's bound, etc.

#### Mutation

The code seems to use mutation of objects pretty liberally, which I think is dangerous in a loosely typed language like JS. If you pass an object to a method which *may* attach properties to it, you'd then have to check to see if those properties are defined every time you want to use them afterwards; quite a pain. On top of that, any asynchronous tasks which may have been referencing that object may see its data changed without warning at any time. Functional programming prefers immutable data.

**Comment by avbel** [comment]
Thanks for detailed feedback.

Main goal of this version of lib is using new features of JS.Next. Only Node v10+ (which will be released on October 2018) should be supported. So using  of transpilers or flag `--harmony` is temporal small pain.

Async iterators are started to use in popular js libs for now. For example look at Apollo v 2 (lib for GraphQL). If language has ability to "hide" async calls why don't use it.

About using additional `await` in `for await`. I use it to have ability to use such actions 2 way:
1) `await api.Message.list()` will return async iterator
2) but `await api.Message.list({page: 1, size: 100})` will return simple list

Decision to use or not async iterators is made after first http request (response header 'Link' is used for that). So I had to use additional `await`.

About naming like api.Calls.get. It was used in current stable release. I left such naming for compatibility

About `cancelToken`. It is  optional. And it is interface object. If you don't like to use implementation of `axios` you can write own (you should implement some functions for that).

I don't see any reasons don't use Proxy here.  Why the lib should prepare all apis if client app use only 2-3 of them (I know in this lib it is small optimization)?

About mutations. I'll recheck code to make it more immutable. Thanks

**Comment by a-type** [comment]
Where are your version target goals coming from? Is there data about which Node versions our users are on, or request for us to support? Our documentation currently claims support for LTS, which seems reasonable. However, as you said, v10 isn't LTS until October. If we're discussing the SDK now, it seems premature to target a version we won't officially support for another 5 months while leaving behind v8, which is the current LTS.

I understand the distinction between the two ways to use `list`, but I was trying to indicate that I think having 2 completely different usages for a function based on the parameters passed in is confusing, and that both usages have limitations which I think may prove too constricting. I maintain my support for simpler, more straightforward usage as the default, and providing tools to enable more advanced / cutting edge workflows for users who care about such things. I suspect that the majority of all SDK users out there just want a library which will connect them to a service without having to think too much. They want to save their thinking for their real business use case, which doesn't involve our SDK. If they are already adept at using async iterators, they'll be happy to use them. But if they are not, my experience as an SDK user indicates that having to learn a new pattern or sift through ambiguous usages will result in an unhappy experience and probably discourage users from using the SDK at all.

As for backwards compatibility, it seems like a major version release is the perfect time to ditch old non-standard naming conventions.

Finally, regarding internal code. For internal projects, I think it's fine to use whatever clever tricks are available if your team agrees on it. But part of the objective for open-sourcing a tool is to invite the community to contribute. That objective means that encouraging outside contribution by providing clean, readable, easy-to-follow code becomes a core consideration in development. We want users to feel empowered to fix bugs they encounter or add new requested features themselves. To do that, I think we should avoid code which uses excessive rebinding, indirection, and really almost anything beyond standard language conventions. Proxy is very powerful, but a lot of powerful tools become burdens. I don't see that the complicated Proxy behavior is really necessary to achieve the functionality represented in the SDK, which is really fairly simple. The modest memory gains by using it do not outweigh the cost I think it will have in terms of discouraging outside contribution.
