### ISSUE TITLE
Travis Badge should display status for the master branch only

### ISSUE THREAD

**Issue by fuchsnj** [Bandwidth/node-bandwidth#15]

**Comment by nguyer** [comment]
Doesn't it do this already?

**Comment by fuchsnj** [comment]
No, it is currently set to
`https://api.travis-ci.org/bandwidthcom/node-bandwidth.png`
but it should be
`https://api.travis-ci.org/bandwidthcom/node-bandwidth.png?branch=master`

**Comment by nguyer** [comment]
Ah nevermind. You're right. Thanks.
