### ISSUE TITLE
Are there release notes for 3.0.0?

### ISSUE THREAD

**Issue by natesilva** [Bandwidth/node-bandwidth#151]
Hi,

I see that the version was bumped from 2.x to 3.0.0. Are there any release notes?

Regards,
Nate

**Comment by jmulford-bw** [comment]
Hey Nate,

My apologies for not including release notes. The only breaking change is that we no longer support versions of node less than 6.

I'll add a release note to the readme and close this issue after that.

Thanks,

Jacob

**Comment by natesilva** [comment]
Sounds good. Thanks!
