### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by amiller-gh** [Bandwidth/node-bandwidth#157]
Hello @Aubron!

Sorry to be *__that__* person on GitHub (nobody likes *__that__* person...) but wanted to bump getting a release cut with #156 included so I can get my product off of a commit-pegged version and to a proper semver release.

Is there a better channel to join for process requests like this so I can help keep your issues tab clean?

**Comment by ghost** [comment]
Apologies on the delay.

Live on [npm](https://www.npmjs.com/package/node-bandwidth/v/3.0.3)
