### ISSUE TITLE
Updated for V2

### ISSUE THREAD

**Issue by lukeescude** [Bandwidth/node-bandwidth#159]
Any hopes of this node package being fully updated to support all the endpoints and capabilities of Bandwidth's V2 API? (phone number ordering, etc.)

Thanks!

**Comment by jmulford-bw** [comment]
Hey @lukeescude,

We are not planning on adding any more V2 functionality into this package. Our "getting started" V2 guide can be found at https://dev.bandwidth.com/sdks/node.html, and our repos can be found at https://github.com/Bandwidth/node-messaging, https://github.com/Bandwidth/node-numbers, and https://github.com/Bandwidth/node-voice. In addition our BXML package can be found at https://www.npmjs.com/package/@bandwidth/bxml (currently there is no public facing repo for this)

Hope this helps!

Jacob
