### ISSUE TITLE
Add JSHint and JSCS with Gulp or Grunt

### ISSUE THREAD

**Issue by nguyer** [Bandwidth/node-bandwidth#18]
Right now the project does not use any sort of build tool. In addition there is no enforcement of any sort of consistent style, or automatic linting. We should add Gulp or Grunt to our project so that we can establish some objective rules around "acceptable" code contributions.

**Comment by nguyer** [comment]
I suggest using Gulp. Does anyone else have input on this?

**Comment by jagoda** [comment]
+1 for Gulp

@bandwidthcom/javascript

**Comment by fuchsnj** [comment]
I vote on Gulp also.

**Comment by wtcross** [comment]
I have no preference.

**Comment by wtcross** [comment]
I think a good way to decide would be to submit a PR with the proposed `gulpfile.js` for review. This is what was done when we decided on our typical `Gruntfile.js`. If it is better than Grunt then great, I'm all for it.

**Comment by wtcross** [comment]
I change my vote to Gulp.

**Comment by nguyer** [comment]
I am leaning toward Gulp as well. @wtcross That is what I am planning on doing. I actually have one almost done.

**Comment by nguyer** [comment]
Implemented in https://github.com/bandwidthcom/node-bandwidth/pull/22
