### ISSUE TITLE
Improving efficiency and consistency of Message.create 

### ISSUE THREAD

**Issue by EdHintz** [Bandwidth/node-bandwidth#5]
**Message.create** has different behavior and return results depending on whether one message or a list of messages is passed to the function.    

When you call **Message.create** with a list of messages the callback for success is an array of objects containing the id of the message if that message was successfully sent, otherwise it is the error for that given message.  If the caller wants more details about a particular message that was sent, they call **Message.get** and pass in the id.

When you call **Message.create** with a single message it behaves differently.

**Expected**: An array of one object that contains the id of the message or the error if it failed.  If I want more details about the message (which I generally do not need) I can call **Message.get** with the id.

**Actual**: Single object with details about the message sent.  This makes processing the result more complex than it needs to be.  If I always get an array even if it is an array of 1 for a single message I can process the results the same regardless of the number of messages sent.  Moreover, **Message.create** when passed a single message internally calls **Message.get** with the id of the message (this does not happen if you pass a list of messages).  This means the package makes an extra REST call back to the Bandwidth Application Server that I did not ask for and may not need.   We send a large number of single messages that results in twice as many REST calls to the Bandwidth Application Server than necessary.

As a user of node-bandwidth, I'd like the same structure sent to the call back of **Message.create** so that processing the result is simpler.

As a user of node-bandwidth, I'd like Message.create to not call Message.get internally to avoid an unnecessary REST call to the Bandwidth Application Server.  If I need the message details, I can call **Message.get** explicitly.

**Comment by avbel** [comment]
I ported this lib from java library. It uses next logic of creation of anything:
AnyClass.create() 
1) sends POST request to create instance
2) sends GET request to return created instance info

If we are going to change this logic we should do that for all types (not Message only) and for all libraries ( .net, ruby, etc)

Now Message.create() on nodejs  works similar Message.Create on C# and Ruby

**Comment by wtcross** [comment]
I think the "one pattern fits all" approach is going to limit maintainability, usage by community, and overall progress in general of the SDKs. It will potentially lead to fighting the implementation language to force in the pattern. For example, global credentials in Node is a bad idea. The module will be cached and any other module will be able to access the credentials if set globally.

**Comment by wtcross** [comment]
The API is already uniform. No reason for this requirement that all SDKs have the exact same interface, in my opinion. The purpose of an SDK should be to increase developer productivity for a specific language. That means using that languages practices, conventions, and patterns. If that isn't done the project is at risk for 0 contributions from "real" public people.

**Comment by ffranco-daitan** [comment]
I agree that the pattern of creating then "getting" the resource seems very inefficient and unnecessary.
