### ISSUE TITLE
Passing in a client object to send SMS does not work

### ISSUE THREAD

**Issue by nguyer** [Bandwidth/node-bandwidth#8]
The `README.md` states that one should be able to create a `client` object and pass it into any of the methods to make API calls like this:

``` javascript
var client = new catapult.Client("userId", "apiToken", "apiSecret");
catapult.Message.create(client, {from: "+19195551212", to: "+191955512142", text: "Test"}, function(err, message){...});
```

This does not work. Only using the global `client` object, does sending SMS actually work.

**Comment by avbel** [comment]
I have tested.

``` js
    var catapult = require("node-bandwidth");
    catapult.Client.globalOptions.userId = "u-xxxxx";
    catapult.Client.globalOptions.apiToken = "t-xxxxx";
    catapult.Client.globalOptions.apiSecret = "xxxxxx";
    catapult.Message.create( {to: "+12520000000", from: "+1910000000", text: "test"}, function(err, message){
      if(err){
        return console.error("Error: %s", err);
      }
      console.log(message);
    });
```

And

``` js
    var catapult = require("node-bandwidth");
        var client = new catapult.Client("u-xxxxx", "t-xxxxx", "xxxxx");
    catapult.Message.create(client,  {to: "+12520000000", from: "+1910000000", text: "test"}, function(err, message){
      if(err){
        return console.error("Error: %s", err);
      }
      console.log(message);
    });
```

Both pieces of code work fine.

`node-bandwidth` is 1.0.8, `node` is 0.12.0. Tested on Mac OS X 10.10.3 and Debian Linux 8

**Comment by wtcross** [comment]
Could you try it again with node 0.10.x? It  isn't working for me either. I
see the Travis build uses 0.10, but there might be something odd going on.
I'll put a stack trace in the issue with my node and client versions too
within a couple of hours.

**Comment by avbel** [comment]
Node 0.10.38. Same result

**Comment by wtcross** [comment]
[Here](https://gist.github.com/wtcross/9ebe39e3d4445a9ddaf4) is a globally configured client example. It works.

[Here](https://gist.github.com/wtcross/bfd93a901942d1611e26) is a non-globally configured client example. It also works.

I'm using node v0.10.38 on Ubuntu 15.04. Thanks for the thoroughness in checking out @avbel !

**Comment by wtcross** [comment]
I was basing my previous comment off memory.

**Comment by nguyer** [comment]
Okay, this actually is working for me now. I'm not sure what was different when it didn't work before. Thanks guys!
